# Generated by Django 5.0 on 2023-12-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='new', max_length=100),
            preserve_default=False,
        ),
    ]
